apiVersion: v1
kind: Pod
metadata:
  name: pod-front
  labels:
    name: pod-front
spec:
  containers:
  - name: storeoncontainer
    image: srtg/storeoncontainer:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-productservice
  labels:
    name: pod-productservice
spec:
  containers:
  - name: geekshopping-productapi
    image: srtg/geekshopping-productapi:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
