// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.ProductApi.Infrastructure.Context;

#nullable disable

namespace Store.ProductApi.Migrations
{
    [DbContext(typeof(Infrastructure.Context.AppContext))]
    [Migration("20240422122424_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Store.ProductApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d6bcf0d-5478-420e-beb8-de98111b89e2"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/2_no_internet.jpg?raw=true",
                            Name = "Camiseta No Internet",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = new Guid("c29c440a-080c-4e16-bb9c-ed7effa2632d"),
                            Category = "Action Figure",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/3_vader.jpg?raw=true",
                            Name = "Capacete Darth Vader Star Wars Black Series",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = new Guid("9a472b1f-8bbb-4c54-b353-1a77811aa490"),
                            Category = "Action Figure",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/4_storm_tropper.jpg?raw=true",
                            Name = "Star Wars The Black Series Hasbro - Stormtrooper Imperial",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = new Guid("675eafa6-33ee-4c37-b18d-74040def14f9"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/5_100_gamer.jpg?raw=true",
                            Name = "Camiseta Gamer",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = new Guid("ef3e0b60-125e-4662-88c1-fe8d13b4afd7"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/6_spacex.jpg?raw=true",
                            Name = "Camiseta SpaceX",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("07d4ff45-a4b3-4cd3-8e09-44a5e1e66b8c"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/7_coffee.jpg?raw=true",
                            Name = "Camiseta Feminina Coffee Benefits",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = new Guid("82d18646-279d-4989-a084-57288b702123"),
                            Category = "Sweatshirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/8_moletom_cobra_kay.jpg?raw=true",
                            Name = "Moletom Com Capuz Cobra Kai",
                            Price = 159.9m
                        },
                        new
                        {
                            Id = new Guid("9bce37a3-985e-4eb2-8043-bea5ef83ee9e"),
                            Category = "Book",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/9_neil.jpg?raw=true",
                            Name = "Livro Star Talk – Neil DeGrasse Tyson",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = new Guid("6c93f102-65bc-4b34-9217-401f5f1f6940"),
                            Category = "Action Figure",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/10_milennium_falcon.jpg?raw=true",
                            Name = "Star Wars Mission Fleet Han Solo Nave Milennium Falcon",
                            Price = 359.99m
                        },
                        new
                        {
                            Id = new Guid("96f5fb5d-57b7-46dc-8c7f-5e0a04aca09b"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/11_mars.jpg?raw=true",
                            Name = "Camiseta Elon Musk Spacex Marte Occupy Mars",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("8cd2629e-67fc-4d81-b283-fab42e2698ac"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/12_gnu_linux.jpg?raw=true",
                            Name = "Camiseta GNU Linux Programador Masculina",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("d9aea7cd-9124-4642-8392-749b0061b64e"),
                            Category = "T-shirt",
                            Description = "Quisque at urna sapien. Maecenas placerat tincidunt nibh, sed fringilla nibh tempus eget. Nullam vitae nisi sit amet erat mattis lacinia vitae ut nisi. Pellentesque tortor mauris, maximus sed tincidunt in, vehicula ut tellus. Duis mollis leo a elit mollis, sed efficitur risus mollis. Sed congue condimentum erat et maximus. Praesent porttitor et enim vel rutrum. Nunc vitae ipsum ut dui congue tincidunt. Aenean at purus non arcu maximus rhoncus non id nisi.",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/13_dragon_ball.jpg?raw=true",
                            Name = "Camiseta Goku Fases",
                            Price = 59.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
